# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ProfilerSA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProfilerSA
  pod 'TwitterKit'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Alamofire', '~> 4.7'

  target 'ProfilerSATests' do
    inherit! :search_paths
    # Pods for testing
  end

end
