# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ProfilerSA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProfilerSA
  pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2', :submodules => true
  pod 'SwiftyJSON', '~> 4.0'

  target 'ProfilerSATests' do
    inherit! :search_paths
    # Pods for testing
  end

end
